"""name to username

Revision ID: 9d923484f4c7
Revises: 7b8b1df2ad3c
Create Date: 2025-07-14 11:54:11.501485

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9d923484f4c7"
down_revision: Union[str, None] = "7b8b1df2ad3c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(length=255), nullable=False))
    op.add_column("users", sa.Column("password", sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, "users", ["username"])
    op.drop_column("users", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "password")
    op.drop_column("users", "username")
    # ### end Alembic commands ###
